FROM ubuntu:14.04
MAINTAINER jhoncbuendia@gmail.com
RUN apt-get update
RUN apt-get -y install python-pip
RUN pip install django==1.8
RUN pip install django_admin_bootstrapped
RUN pip install django-cors-headers
RUN pip install djangorestframework
WORKDIR /home
